### ISSUE TITLE
Definition of task_us()

### ISSUE THREAD

**Issue by imrulkk89** [pietern/avr-tasks#2]
Where is the definition of task_us() ? My Atmel Studio 7 giving error. .... 
![task_us](https://cloud.githubusercontent.com/assets/3744387/11284085/23ca03e8-8f32-11e5-8f93-c80cf9ab1442.jpg)

**Comment by pietern** [comment]
Ah, the example should be updated.

I changed the time counters to be optional in this commit: 0203a3cf4b72c6f910810e7f20fba9d7a6c57014 . If you replace `task_us` with `task_usec` and specify the preprocessor definition `-DTASK_COUNT_USEC` you should be good to go.

**Comment by pietern** [comment]
@imrulkk69 Did this fix your issue? If so, I'll update the code in the repo.
